apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: K0smotronControlPlane
metadata:
  name: {{ include "k0smotroncontrolplane.name" . }}
spec:
  replicas: {{ .Values.controlPlaneNumber }}
  version: {{ .Values.k0s.version | replace "+" "-" }}
  {{- with .Values.k0smotron.service }}
  service:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  controllerPlaneFlags:
  - "--enable-cloud-provider=true"
  - "--debug=true"
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    metadata:
      name: k0s
    spec:
      network:
        provider: calico
        calico:
          mode: vxlan
      extensions:
        helm:
          repositories:
            - name: mirantis
              {{- if .Values.extensions.chartRepository }}
              url: {{ .Values.extensions.chartRepository }}
              {{- else }}
              url: https://charts.mirantis.com
              {{- end }}
            - name: azuredisk-csi-driver
              {{- if .Values.extensions.chartRepository }}
              url: {{ .Values.extensions.chartRepository }}
              {{- else }}
              url: https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
              {{- end }}
          charts:
            - name: cloud-provider-azure
              namespace: kube-system
              chartname: mirantis/cloud-provider-azure
              version: 1.31.2
              order: 1
              values: |
                cloudControllerManager:
                  cloudConfigSecretName: azure-cloud-provider
                  nodeSelector:
                    node-role.kubernetes.io/control-plane: null
                  imageRepository: {{ .Values.extensions.imageRepository }}
                cloudNodeManager:
                  imageRepository: {{ .Values.extensions.imageRepository }}
            - name: azuredisk-csi-driver
              namespace: kube-system
              chartname: azuredisk-csi-driver/azuredisk-csi-driver
              version: 1.30.3
              order: 2
              values: |
                image:
                  baseRepo: {{ .Values.extensions.imageRepository }}
                controller:
                  cloudConfigSecretName: azure-cloud-provider
                node:
                  cloudConfigSecretName: azure-cloud-provider
                linux:
                  kubelet: "/var/lib/k0s/kubelet"
